phases:
- phase: VS_Latest
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  steps:
  - task: GitVersion@3
    inputs:
      updateAssemblyInfo: false   
      
  - task: NuGetToolInstaller@0
    inputs:
        versionSpec: 4.7.0
        checkLatest: false

  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: Rx.NET\Source\System.Reactive.sln
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal

  - task: MSBuild@1
    inputs:
      solution: Rx.NET\Source\System.Reactive.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary /bl:$(build.artifactstagingdirectory)\build-lib.binlog
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
  
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: drop
      publishLocation: Container
  